/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
import Head from 'next/head';
import Card from '../components/card/Card';
import Concept from '../components/Concept/Concept';
import Cta from '../components/Cta/Cta';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/kkr5ojt.css" />
      </Head>

      <main className={styles.main}>
        <Card />
        <Concept />
      </main>
      <Cta />
    </div>
  );
}
